name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run release-please for client
        id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-client-config.json
          manifest-file: .release-please-manifest-client.json
          skip-labeling: true

  release-please-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run release-please for server
        id: release
        uses: googleapis/release-please-action@v4
        with:
          config-file: release-please-server-config.json
          manifest-file: .release-please-manifest-server.json
          skip-labeling: true
